language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: Q/ako62E7ijm7yfL8GnW9rRciEJkpxEGitDJeOLESgMpEjoldN5rcla7MnWn32BGjWzh6ZcBdOie1U3oWmbLP7bYOVthtl0lmHH40e+HKnUO9P0VgAlkmW+0PjU6m1bCrQaVjcqnvQ9SCluPsutqn5FxXCLgiScuGY6x3wE7IaNp6jZCfjncgiwAfiLMX/0sSVH6s3jJiy6a/dlY2FTPfn2Cj/uVB1uTwxyro1556re7Cc64glbDPztRicHPGOBpdcBQpoYyJ01yJocj/SwcgoKERHGsVzSqYbhrCuT1XWk9oLalbgVY5Kbuk9vIwuwpGakp89ZLRCQyKYPmcYfXcjv/j5qnALLzLGvO9D3VU0+kKOZtEyMZa4wAeyvDGl5ZzeGUTXshKQyuuAFtguOLUbK+e3X51/If7wQ/GeR6UuN0KXxao3yQoaTrUYwJEoCTGjqT75kH/oT7nkpc+VWj0sYcEM/usATnVkJ6XqeEEj+BjdI9nPP41E3nakcznOkqoeeQJ82uB0zn/czOaJFhQkridfw28qhxTJt/OKLnQM8Nn0augVuUia7zzfB7kHN5shLV0xwZqw4sBQRFv7RyUwThcGXGI8jDZRcMkbX3l93exco9py9IICSdP0k3Yg8FHyA4xplpIvhVCZoi7VZL38urcHDoNF0Z9vSn8vWJKrQ=
